/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MonkeytypeIndexRouteImport } from './routes/monkeytype/index'
import { Route as GithubIndexRouteImport } from './routes/github/index'
import { Route as GithubFileSplatRouteImport } from './routes/github/file.$'
import { Route as GithubDirSplatRouteImport } from './routes/github/dir.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonkeytypeIndexRoute = MonkeytypeIndexRouteImport.update({
  id: '/monkeytype/',
  path: '/monkeytype/',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubIndexRoute = GithubIndexRouteImport.update({
  id: '/github/',
  path: '/github/',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubFileSplatRoute = GithubFileSplatRouteImport.update({
  id: '/github/file/$',
  path: '/github/file/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubDirSplatRoute = GithubDirSplatRouteImport.update({
  id: '/github/dir/$',
  path: '/github/dir/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/github': typeof GithubIndexRoute
  '/monkeytype': typeof MonkeytypeIndexRoute
  '/github/dir/$': typeof GithubDirSplatRoute
  '/github/file/$': typeof GithubFileSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/github': typeof GithubIndexRoute
  '/monkeytype': typeof MonkeytypeIndexRoute
  '/github/dir/$': typeof GithubDirSplatRoute
  '/github/file/$': typeof GithubFileSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/github/': typeof GithubIndexRoute
  '/monkeytype/': typeof MonkeytypeIndexRoute
  '/github/dir/$': typeof GithubDirSplatRoute
  '/github/file/$': typeof GithubFileSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/github'
    | '/monkeytype'
    | '/github/dir/$'
    | '/github/file/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/github' | '/monkeytype' | '/github/dir/$' | '/github/file/$'
  id:
    | '__root__'
    | '/'
    | '/github/'
    | '/monkeytype/'
    | '/github/dir/$'
    | '/github/file/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GithubIndexRoute: typeof GithubIndexRoute
  MonkeytypeIndexRoute: typeof MonkeytypeIndexRoute
  GithubDirSplatRoute: typeof GithubDirSplatRoute
  GithubFileSplatRoute: typeof GithubFileSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monkeytype/': {
      id: '/monkeytype/'
      path: '/monkeytype'
      fullPath: '/monkeytype'
      preLoaderRoute: typeof MonkeytypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github/': {
      id: '/github/'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github/file/$': {
      id: '/github/file/$'
      path: '/github/file/$'
      fullPath: '/github/file/$'
      preLoaderRoute: typeof GithubFileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github/dir/$': {
      id: '/github/dir/$'
      path: '/github/dir/$'
      fullPath: '/github/dir/$'
      preLoaderRoute: typeof GithubDirSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GithubIndexRoute: GithubIndexRoute,
  MonkeytypeIndexRoute: MonkeytypeIndexRoute,
  GithubDirSplatRoute: GithubDirSplatRoute,
  GithubFileSplatRoute: GithubFileSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
