/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GithubPathRouteImport } from './routes/$githubPath'
import { Route as IndexRouteImport } from './routes/index'

const GithubPathRoute = GithubPathRouteImport.update({
  id: '/$githubPath',
  path: '/$githubPath',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$githubPath': typeof GithubPathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$githubPath': typeof GithubPathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$githubPath': typeof GithubPathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$githubPath'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$githubPath'
  id: '__root__' | '/' | '/$githubPath'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GithubPathRoute: typeof GithubPathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$githubPath': {
      id: '/$githubPath'
      path: '/$githubPath'
      fullPath: '/$githubPath'
      preLoaderRoute: typeof GithubPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GithubPathRoute: GithubPathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
