/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FileSplatRouteImport } from './routes/file.$'
import { Route as DirSplatRouteImport } from './routes/dir.$'
import { Route as ContentTypeSplatRouteImport } from './routes/$contentType.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FileSplatRoute = FileSplatRouteImport.update({
  id: '/file/$',
  path: '/file/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DirSplatRoute = DirSplatRouteImport.update({
  id: '/dir/$',
  path: '/dir/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentTypeSplatRoute = ContentTypeSplatRouteImport.update({
  id: '/$contentType/$',
  path: '/$contentType/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$contentType/$': typeof ContentTypeSplatRoute
  '/dir/$': typeof DirSplatRoute
  '/file/$': typeof FileSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$contentType/$': typeof ContentTypeSplatRoute
  '/dir/$': typeof DirSplatRoute
  '/file/$': typeof FileSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$contentType/$': typeof ContentTypeSplatRoute
  '/dir/$': typeof DirSplatRoute
  '/file/$': typeof FileSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$contentType/$' | '/dir/$' | '/file/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$contentType/$' | '/dir/$' | '/file/$'
  id: '__root__' | '/' | '/$contentType/$' | '/dir/$' | '/file/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentTypeSplatRoute: typeof ContentTypeSplatRoute
  DirSplatRoute: typeof DirSplatRoute
  FileSplatRoute: typeof FileSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file/$': {
      id: '/file/$'
      path: '/file/$'
      fullPath: '/file/$'
      preLoaderRoute: typeof FileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dir/$': {
      id: '/dir/$'
      path: '/dir/$'
      fullPath: '/dir/$'
      preLoaderRoute: typeof DirSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$contentType/$': {
      id: '/$contentType/$'
      path: '/$contentType/$'
      fullPath: '/$contentType/$'
      preLoaderRoute: typeof ContentTypeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentTypeSplatRoute: ContentTypeSplatRoute,
  DirSplatRoute: DirSplatRoute,
  FileSplatRoute: FileSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
